### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ZachGlassman** [thedataincubator/forecaster#1]
Please alter the README to include instructions regarding

1. installing the local python environment
2. running local tests

**Comment by sdorsher** [comment]
cat conda_requirements.txt | conda install 
doesn't work for fairly obvious reasons. I am not sure how to read one line at a time in bash, though I know how to read one file at a time in bash.

**Comment by sdorsher** [comment]
I am not currently working on this, I did this installation by hand. I ignored "detect-secrets" and "mock".  I did not upgrade my conda version itself.

However, it is not possible to do this simply using either
cat conda_requirements.txt | conda install 
or 
conda install < conda_requirements.txt

Some line by line script is needed. Does anyone remember how we did this in the flask framework? I can't find the instructions. 

Otherwise, it's possible to write a script. It's okay to modify the way that I structured the bokeh version, without closing the issue, if necessary. It is not easy to write a bash script that parses line by line. I suggest python.

**Comment by ZachGlassman** [comment]
Please open a pull request with the proposed changes to the readme.  There is a flag you can pass to conda to allow installation from a file.

**Comment by sdorsher** [comment]
conda install --file conda_requirements.txt
conda install --file requirements.txt
conda install --file dev-requirements.txt

**Comment by sdorsher** [comment]
Done, though I think I screwed it up the first time. Thank you.

Steven

**Comment by ZachGlassman** [comment]
please open a pull request with these changes in the readme.  Additionally, files in requirements.txt should be installed with pip

**Comment by sdorsher** [comment]
How do I do that? I don’t see an option to specify how I open a pull request.

Steven

**Comment by ZachGlassman** [comment]
@sdorsher Please work on the bokeh upgrade, @josylman please take this.  The install instructions should be in the README

**Comment by sdorsher** [comment]
cat conda-requirements.txt | conda install

I can't figure out why this doesn't work. Honestly.

**Comment by ZachGlassman** [comment]
there is an option to install from a file

**Comment by sdorsher** [comment]
I can’t alter the readme if you won’t approve my changes. Issue closed.
